# Generated by Django 5.0 on 2024-09-17 20:13

import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('number', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('instagram', models.CharField(max_length=255, verbose_name='اینستاگرام')),
                ('email', models.CharField(max_length=255, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='نقشه')),
            ],
            options={
                'verbose_name': 'تنظیمات تماس باما',
                'verbose_name_plural': 'تنظیمات تماس باما',
            },
        ),
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوعات',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شده؟')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('number', models.CharField(max_length=255, verbose_name='شماره')),
                ('text', models.TextField(verbose_name='متن')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contactsubject', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'فرم تماس باما',
                'verbose_name_plural': 'فرم های تماس باما',
            },
        ),
    ]
