# Generated by Django 5.0 on 2024-09-17 20:13

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='نام شهر')),
                ('on_home', models.BooleanField(default=False, help_text='8 شهر پربازدید در صفحه اسلی و برای دسترسی سریع کاربر نمایش داده میشوند', verbose_name='شهر پربازدید؟')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استانها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ServiceExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نکته')),
            ],
            options={
                'verbose_name': 'نکته',
                'verbose_name_plural': 'نکات تکمیلی',
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='سوال')),
                ('text', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='HomeCareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی باشد به صورت خودکار از عنوان استفاده میکند', null=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='عکس')),
                ('meta_description', models.CharField(blank=True, help_text='Meta Description Tag For Seo', max_length=500, null=True, verbose_name='تگ توضیحات')),
                ('meta_keywords', models.CharField(blank=True, help_text='Meta Keywords Tag For Seo', max_length=500, null=True, verbose_name='تگ کلمات کلیدی')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_children', to='service.homecarecategory', verbose_name='دسته پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندیها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='HomeCareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='آیکون')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.homecarecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'خدمت در منزل',
                'verbose_name_plural': 'خدمات در منزل',
                'ordering': ('title', 'category'),
            },
        ),
        migrations.CreateModel(
            name='HomeCareServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت خدمات',
            },
        ),
    ]
