# Generated by Django 5.0 on 2024-09-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecareserviceprice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.homecarecompany', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='homecareserviceprice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.homecareservice', verbose_name='خدمت'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='service.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='serviceextrainfo',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='service.homecareservice', verbose_name='خدمات'),
        ),
        migrations.AddField(
            model_name='servicefaq',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='service.homecareservice', verbose_name='خدمات'),
        ),
    ]
