# Generated by Django 5.0 on 2024-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک های مفید',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('site_url', models.URLField(null=True, verbose_name='آدرس سایت')),
                ('android_url', models.CharField(blank=True, max_length=700, null=True, verbose_name='آدرس دانلود اپ اندروید')),
                ('iphone_url', models.URLField(blank=True, null=True, verbose_name='آدرس دانلود اپ آیفون')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='لوگو')),
                ('logo_mobile', models.ImageField(null=True, upload_to='', verbose_name='لوگو موبایل')),
                ('fav_icon', models.ImageField(null=True, upload_to='', verbose_name='fav_icon')),
                ('meta_keywords', models.TextField(null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.TextField(null=True, verbose_name='Meta Description')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('number', models.TextField(verbose_name='شماره تماس')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='متن اول صفحه اصلی')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='متن دوم صفحه اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='SiteSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.URLField(verbose_name='لینک')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
