# Generated by Django 5.0 on 2024-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='سفارش شده')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم های سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='HomeCareOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sent_head_admin', models.BooleanField(default=False)),
                ('sms_send_city_managers', models.BooleanField(default=False)),
                ('sms_send_company_admin', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('status', models.CharField(choices=[('ongoing', 'خدمات پیش رو'), ('onmission', 'اعزام نیرو'), ('previous', 'خدمات گذشته'), ('canceled', 'خدمات لغو شده')], max_length=255, verbose_name='وضعیت')),
                ('cart_in_place', models.CharField(choices=[('online', 'آنلاین'), ('place', 'در محل')], max_length=255, null=True, verbose_name='نوع پرداخت')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='هزینه نهایی پرداخت شده')),
                ('pay_token', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='کد پیگیری')),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('due_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='تاریخ اعزام نیرو')),
                ('due_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعت اعزام نیرو')),
                ('due_date_time', models.DateTimeField(blank=True, null=True, verbose_name='ساعت و تاریخ اعزام نیرو')),
                ('invite_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بیمار')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('zip_code', models.CharField(max_length=10, verbose_name='کدپستی')),
                ('plak', models.CharField(max_length=3, verbose_name='پلاک')),
                ('number_1', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('number_2', models.CharField(max_length=11, verbose_name='شماره ثابت')),
            ],
            options={
                'verbose_name': 'اطلاعات آدرس سفارش',
                'verbose_name_plural': 'اطلاعات آدرس سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sent_head_admin', models.BooleanField(default=False, verbose_name='ارسال پیام برای ادمین کل')),
                ('sms_send_city_managers', models.BooleanField(default=False, verbose_name='ارسال پیام برای مدیر شهری')),
                ('sms_send_company_admin', models.BooleanField(default=False, verbose_name='ارسال پیام برای ادمین شرکتی')),
                ('sms_send_admin_for_onmission', models.BooleanField(default=False, verbose_name='ارسال پیام به مدیر شهری برای پیگیری اعزام نیرو')),
                ('status', models.CharField(choices=[('ongoing', 'خدمات پیش رو'), ('onmission', 'اعزام نیرو'), ('previous', 'خدمات گذشته'), ('canceled', 'خدمات لغو شده')], default='ongoing', max_length=255, verbose_name='وضعیت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده')),
            ],
            options={
                'verbose_name': 'آیتم های سفارش',
                'verbose_name_plural': 'آیتم های سفارش',
            },
        ),
    ]
