# Generated by Django 5.0 on 2024-09-17 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('service', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cart.cart', verbose_name='سبدخرید'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.homecareserviceprice', verbose_name='خدمات'),
        ),
        migrations.AddField(
            model_name='homecareorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.useraddress', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='homecareorder',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart', verbose_name='سبد خرید'),
        ),
        migrations.AddField(
            model_name='homecareorder',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='homecareorder',
            name='ordered_companies',
            field=models.ManyToManyField(help_text='کمپانی های که خدماتشان خریداری شده است در اینجا نمایش داده میشود', null=True, related_name='ordered_companies', to='user.homecarecompany', verbose_name='کمپانی'),
        ),
        migrations.AddField(
            model_name='homecareorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.homecareorder', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.homecarecompany', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.homecareorder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.homecareserviceprice', verbose_name='خدمات'),
        ),
    ]
